spring:
  application:
    name: book-service
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
user:
  sendreport:
    uri: http://localhost:8080/api/v1/report
  api:
    version: v1
server:
  port: 0
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
        defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

